version: "3.9"

services:
  postgres:
    profiles: ["dev"]
    ports:
      - "${POSTGRES_HOST_PORT:-5432}:5432"

  minio:
    profiles: ["dev"]
    ports:
      - "${MINIO_HOST_PORT:-9000}:9000"
      - "${MINIO_CONSOLE_HOST_PORT:-9001}:9001"

  backend:
    profiles: ["dev"]
    ports:
      - "${BACKEND_HOST_PORT:-8080}:8080"

  tiling:
    profiles: ["dev"]
    ports:
      - "${TILING_HOST_PORT:-8000}:8000"
