services:
  db:
    image: postgis/postgis:16-3.4
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
    volumes:
      - dbdata:/var/lib/postgresql/data

  api:
    build: ./apps/api
    depends_on:
      - db
    environment:
      SPRING_PROFILES_ACTIVE: dev
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: ${POSTGRES_DB}
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${API_PORT}:8080"

  tile-server:
    build: ./apps/tile-server
    environment:
      S3_ENDPOINT: ${S3_ENDPOINT}
      S3_BUCKET: ${S3_BUCKET}
    ports:
      - "${PY_PORT}:8000"

  web:
    build: ./apps/frontend
    ports:
      - "${WEB_PORT}:5173"
    depends_on:
      - api
      - tile-server

  objectstore:
    image: minio/minio:latest
    command: server /data --address :9000 --console-address :9001
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - s3data:/data

volumes:
  dbdata:
  s3data:
