server:
  port: 8080

spring:
  application:
    name: histoflow-backend
  
  # H2 Database (for future use)
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: false

# MinIO Configuration (S3-compatible object storage)
minio:
  endpoint: http://minio:9000          # internal (Docker network)
  public-endpoint: http://localhost:9000
  access-key: minioadmin
  secret-key: minioadmin
  buckets:
    tiles: histoflow-tiles
    raw: unprocessed-slides

tiling:
  base-url: http://localhost:8000

# Logging Configuration
logging:
  level:
    root: INFO
    com.histoflow.backend: DEBUG
    software.amazon.awssdk: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %logger{36} - %msg%n"
